<?php
require_once __DIR__ . '/../config/auth.php'; require_admin();
$serv=$pdo->query("SELECT * FROM servicos ORDER BY id DESC")->fetchAll();
$sug=$pdo->query("SELECT * FROM sugestoes ORDER BY id DESC")->fetchAll();
$msg=take_flash();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel — Conexão Azul Manaus</title><link rel="stylesheet" href="../assets/style.css"></head>
<body><header class="top"><div class="wrap nav"><a class="brand" href="../index.php">Conexão Azul <span>Manaus</span></a><nav><span>Olá, <?=htmlspecialchars($_SESSION['admin_nome'])?></span><a href="logout.php">Sair</a></nav></div></header>
<main class="section wrap"><?php if($msg):?><p class="success"><?=htmlspecialchars($msg)?></p><?php endif;?><div class="admin-head"><div><h1>Painel administrativo</h1><p>Cadastre, edite, desative ou exclua instituições.</p></div><a class="btn" href="servico_form.php">+ Novo serviço</a></div>
<h2>Instituições</h2><div class="table-wrap"><table><tr><th>Nome</th><th>Categoria</th><th>Bairro</th><th>Status</th><th>Ações</th></tr><?php foreach($serv as $s):?><tr><td><?=htmlspecialchars($s['nome'])?></td><td><?=htmlspecialchars($s['categoria'])?></td><td><?=htmlspecialchars($s['bairro'])?></td><td><?=htmlspecialchars($s['status'])?></td><td><a href="servico_form.php?id=<?=$s['id']?>">Editar</a><form class="inline-form" method="post" action="servico_delete.php" onsubmit="return confirm('Excluir este serviço?')"><?=csrf_input()?><input type="hidden" name="id" value="<?=$s['id']?>"><button class="link-button" type="submit">Excluir</button></form></td></tr><?php endforeach;?></table></div>
<h2>Sugestões recebidas</h2><div class="table-wrap"><table><tr><th>Nome</th><th>Categoria</th><th>Bairro</th><th>Status</th><th>Ação</th></tr><?php foreach($sug as $x):?><tr><td><?=htmlspecialchars($x['nome'])?></td><td><?=htmlspecialchars($x['categoria'])?></td><td><?=htmlspecialchars($x['bairro'])?></td><td><?=htmlspecialchars($x['status'])?></td><td><?php if($x['status']==='pendente'):?><form class="inline-form" method="post" action="sugestao_aprovar.php"><?=csrf_input()?><input type="hidden" name="id" value="<?=$x['id']?>"><button class="link-button" type="submit">Aprovar</button></form> · <form class="inline-form" method="post" action="sugestao_rejeitar.php"><?=csrf_input()?><input type="hidden" name="id" value="<?=$x['id']?>"><button class="link-button" type="submit">Rejeitar</button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></table></div></main></body></html>
